[project]
name = "MinecraftLauncher-py"
version = "1.0.0.31"
dependencies = [
    "PySide6 >= 6.11.0",
    "requests == 2.33.1",
    "nuitka >= 4.0.8",
    "qrcode == 8.2",
    "packaging == 26.2",
    "pywin32 == 311; platform_system == 'Windows'",
    "keyring == 25.7.0; platform_system != 'Windows'",
    "cryptography == 47.0.0; platform_system != 'Windows'",
]
requires-python = ">= 3.13"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov"
]

[tool]

[tool.black]
line-length = 79
extend-exclude = "_resources_bundled.py"

[tool.pyright]
pythonPlatform = "All"

[tool.nuitka]
mode = "standalone"
