import logging

from . import CWD, PROJECT_TOML

log = logging.getLogger(__name__)
log.info("Starting pre-build hooks")

module_dir = CWD / "minecraftlauncher"

toml_p = CWD / "pyproject.toml"
ver_mod_path = module_dir / "__version__.py"


version: str = PROJECT_TOML["project"]["version"]
if not isinstance(version, str):
    raise TypeError("pyproject.toml[project][version] is incorrect type!")
log.debug("Detected version: %s", version)
payload = f"""# This file was automatically generated by /scripts/build_hooks.py

VERSION = "{version}"
"""
ver_mod_path.write_text(payload)

log.info("Wrote version info to %s.", ver_mod_path.resolve().absolute())
