SHDIR=$(cd -- "$(dirname -- "${BASH_SOURCE}" )" &> /dev/null && pwd)

cd $SHDIR
cd ..

source ./.venv/lib/activate

python ./resources/compile.py

python -m nuitka \
    --standalone \
    --show-anti-bloat-changes \
    --show-source-changes=minecraftlauncher \
    --python-flag=-m \
    --python-flag=isolated \
    --enable-plugin=pyside6 \
    --include-qt-plugins=sensible,qml \
    --output-dir=./dist \
    --include-module=_json \
    --noinclude-dlls=*.cpp.o \
    --noinclude-dlls=*.qsb \
    --noinclude-data-files=PySide6/qml/QtWebEngine/* \
    --noinclude-data-files=PySide6/qml/Qt5Compat/* \
    --noinclude-data-files=PySide6/qml/QtCharts/* \
    --noinclude-data-files=PySide6/qml/QtDataVisualization/* \
    --noinclude-data-files=PySide6/qml/QtGraphs/* \
    --noinclude-data-files=PySide6/qml/QtLocation/* \
    --noinclude-data-files=PySide6/qml/QtMultimedia/* \
    --noinclude-data-files=PySide6/qml/QtRemoteObjects/* \
    --noinclude-data-files=PySide6/qml/QtScxml/* \
    --noinclude-data-files=PySide6/qml/QtSensors/* \
    --noinclude-data-files=PySide6/qml/QtTest/* \
    --noinclude-data-files=PySide6/qml/QtTextToSpeech/* \
    --noinclude-data-files=PySide6/qml/QtWebChannel/* \
    --noinclude-data-files=PySide6/qml/QtWebSockets/* \
    --noinclude-data-files=PySide6/qml/QtWebView/* \
    --noinclude-data-files=PySide6/qml/Qt/* \
    --noinclude-data-files=PySide6/qml/QtCore/* \
    --noinclude-data-files=PySide6/qml/QtNetwork/* \
    --noinclude-data-files=PySide6/qml/QtPositioning/* \
    --noinclude-data-files=PySide6/qml/QtQuick/Controls/* \
    --noinclude-data-files=PySide6/qml/QtQuick/Dialogs/* \
    --noinclude-data-files=PySide6/qml/QtQuick/Effects/* \
    --noinclude-data-files=PySide6/qml/QtQuick/Layouts/* \
    --noinclude-data-files=PySide6/qml/QtQuick/LocalStorage/* \
    --noinclude-data-files=PySide6/qml/QtQuick/NativeStyle/* \
    --noinclude-data-files=PySide6/qml/QtQuick/Particles/* \
    --noinclude-data-files=PySide6/qml/QtQuick/Pdf/* \
    --noinclude-data-files=PySide6/qml/QtQuick/Scene2D/* \
    --noinclude-data-files=PySide6/qml/QtQuick/Scene3D/* \
    --noinclude-data-files=PySide6/qml/QtQuick/Shapes/* \
    --noinclude-data-files=PySide6/qml/QtQuick/Templates/* \
    --noinclude-data-files=PySide6/qml/QtQuick/tooling/* \
    --noinclude-data-files=PySide6/qml/QtQuick/VectorImage/* \
    --noinclude-data-files=PySide6/qml/QtQuick/VirtualKeyboard/* \
    --noinclude-data-files=PySide6/qml/QtQuick/Window/* \
    --noinclude-data-files=PySide6/qml/QtQuick3D/designer/* \
    --noinclude-data-files=PySide6/qml/QtQuick3D/Effects/* \
    --noinclude-data-files=PySide6/qml/QtQuick3D/lightmapviewer/* \
    --noinclude-data-files=PySide6/qml/QtQuick3D/MaterialEditor/* \
    --noinclude-data-files=PySide6/qml/QtQuick3D/ParticleEffects/* \
    --noinclude-data-files=PySide6/qml/QtQuick3D/Particles3D/* \
    --noinclude-data-files=PySide6/qml/QtQuick3D/SpacialAudio/* \
    --noinclude-data-files=PySide6/qml/QtQuick3D/Xr/* \
    --noinclude-dlls=libQt6DataVisualization*.so \
    --noinclude-dlls=libQt6LabsWaveFrontMesh.so \
    --noinclude-dlls=libQt6Multimedia*.so \
    --noinclude-dlls=libQt6Pdf*.so \
    --noinclude-dlls=libQt6Quick3DParticle*.so \
    --noinclude-dlls=libQt6Quick3DXr.so \
    --noinclude-dlls=*TextToSpeech*.so \
    --noinclude-dlls=*VirtualKeyboard*.so \
    --noinclude-dlls=libQt6Web*.so \
    --noinclude-dlls=libQt6QuickControls2*.so \
    --noinclude-dlls=libQt6Quick3DEffects.so \
    --noinclude-dlls=libQt6QuickEffects.so \
    --noinclude-dlls=Qt6Sensor*.so \
    --noinclude-dlls=*SpacialAudio*.so \
    --noinclude-dlls=Qt6Sql.so \
    --noinclude-dlls=*StateMachine*.so \
    --noinclude-dlls=*Test*.so \
    --noinclude-dlls=*Qt63DAnimation.so \
    --noinclude-dlls=*Qt63DCore.so \
    --noinclude-dlls=*Qt63DExtras.so \
    --noinclude-dlls=*Qt63DInput.so \
    --noinclude-dlls=*Qt63DLogic.so \
    --noinclude-dlls=*Qt63DRender.so \
    --noinclude-dlls=*Qt6Labs*.so \
    --noinclude-dlls=*Qt6QuickDialogs*.so \
    --noinclude-dlls=*Qt6Charts*.so \
    --noinclude-dlls=*Qt6Graphs*.so \
    --noinclude-dlls=*Qt6PositioningQuick.so \
    --noinclude-dlls=*Qt6PositioningQuick.so \
    --noinclude-dlls=*Qt6Quick3DHelpersImpl.so \
    --noinclude-dlls=*Qt6Quick3DSpatialAudio.so \
    --noinclude-dlls=qt*particle*.so \
    --windows-icon-from-ico=./resources/_dist/icon.ico \
    --output-filename=launcher \
    --file-description="Minecraft Launcher written in Python" \
    ./minecraftlauncher