from enum import StrEnum, IntEnum

from ._PortableProfile import PortableProfile

class ChunkUpdatePrioritization(IntEnum):
    THREADED = 0
    SEMI_BLOCKING = 1
    BLOCKING = 2

class FPSLimitAFK(StrEnum):
    AFK = "afk"
    MINIMIZED = "minimized"

class CloudRender(StrEnum):
    TRUE = "true"
    FAST = "fast"
    FALSE = "false"

class GameOption(StrEnum):
    VERSION = "version"
    """int ?-? (required for >1.10-pre1 versions)"""
    MUSIC_VOL = "music"
    """float 0.0-1.0"""
    SOUND_VOL = "sound"
    """float 0.0-1.0"""
    MOUSE_Y_INVERT = "invertYMouse"
    """bool"""
    RENDER_DISTANCE = "viewDistance"
    """int 2-32 (2-16 when >1GB RAM)"""
    GUI_SCALE = "guiScale"
    """0-? (0 = auto select, max scales to resolution)"""
    BOB_VIEW = "bobView"
    """bool"""
    ANAGLYPH_3D = "anaglyph3d"
    """bool"""
    ADV_OPENGL = "advancedOpengl"
    """bool"""
    FPS_LIMIT = "fpsLimit"
    """int 0-260 (0 = vsync; >255 = unlimited)"""
    SMOOTH_LIGHTING = "ao"
    """bool"""
    BIOME_BLENDING = "biomeBlendRadius"
    """int 0-7"""
    ENABLE_VSYNC = "enabledVsync"
    """bool"""
    ENTITY_DISTANCE = "entityDistanceScaling"
    """float 0.5-5.0"""
    ENTITY_SHADOWS = "entityShadows"
    """bool"""
    FORCE_UNICODE = "forceUnicodeFont"
    """bool"""
    JAPANESE_GLYPH = "japaneseGlyphVariants"
    """bool"""
    FOV = "fov"
    """float -1.0 - 1.0"""
    FOV_SCALE = "fovEffectScale"
    """float 0.0-1.0"""
    DARKNESS_SCALE = "darknessEffectScale"
    """float 0.0-1.0"""
    ENCHANT_GLINT_SPEED = "glintSpeed"
    """float 0.0-1.0"""
    ENCHANT_GLINT_STRENGTH = "glintStrength"
    """float 0.0-1.0"""
    PRIORITIZE_CHUNK_UPDATE = "prioritizeChunkUpdates"
    """`int 0-2 || ChunkUpdatePrioritization`"""
    FULLSCREEN = "fullscreen"
    """bool"""
    GAMMA = "gamma"
    """float 0.0-1.0"""
    GRAPHICS_MODE = "graphicsMode"
    """int 0-2 (>=1.16-pre-release-1) int 0-1 (<1.16-pre-release-1)"""
    AFK_FPS_LIMIT = "inactivityFpsLimit"
    """enum `FPSLimitAFK` - "afk" | "minimized\""""
    MIPMAP_LEVEL = "mipmapLevels"
    """int 0-4"""
    NARRATOR = "narrator"
    """int 0-3 (>17w06a/1.12)"""
    PARTICLES = "particles"
    """int 0-2 (`all`<`decreased`<`minimal`, more particles == lower int)"""
    REDUCED_DEBUG = "reducedDebugInfo"
    """bool"""
    RENDER_CLOUDS = "renderClouds"
    """enum `CloudRender` - "true" || "fast" || "false\""""
    SIM_DISTANCE = "simulationDistance"
    """int 5-32 (16 when >1GB RAM)"""
    SCREEN_EFFECT_SCALE = "screenEffectScale"
    """float 0.0-1.0"""
    SOUND_DEVICE = "soundDevice"
    """string, sound device name"""
    AUTO_JUMP = "autoJump"
    """bool"""
    ROTATE_MINECART = "rotateWithMinecart"
    """bool"""
    AUTO_SUGGEST = "autoSuggestions"
    

    # ALIAS
    BRIGHTNESS = GAMMA
    """float 0.0-1.0 (alias for `GAMMA`)"""
    
    # old values (check version before using)
    GAME_DIFFICULTY = "difficulty"
    """int 0-3"""
    FANCY_GRAPHICS = "fancyGraphics"
    """bool"""